测试冲突：
  git did not exit cleanly (code 3)
  git did not exit cleanly (code 128)
